spring:
  application:
    name: customer-service

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure.include: '*'
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled:true
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full

customer.info: Property value backed into the image

jwt.secret: demo

