spec:
  template:
    spec:
      containers:
      - env:
        - name: GREETING_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: spring-boot-config
              key: greeting.message
        - name: GREETING_SECRET
          valueFrom:
            secretKeyRef:
              name: spring-boot-secret
              key: greeting.secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name:  spring-boot-secret
              key: jwt.secret
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name:  spring-boot-secret
              key: spring.datasource.username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  spring-boot-secret
              key: spring.datasource.password