spec:
  template:
    spec:
      containers:
      - env:
        - name: GREETING_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: customer-config
              key: greeting.message
        - name: GREETING_SECRET
          valueFrom:
            secretKeyRef:
              name: customer-secret
              key: greeting.secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name:  customer-secret
              key: jwt.secret
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name:  customer-config
              key: spring.data.mongodb.uri